### PR TITLE
Implement dvm ls.

### PR DESCRIPTION
**Pull request by smashwilson**
Should be pretty easy.

### CODE REVIEW

**Comment by smashwilson** [comment]
There we go:

```
$ dvm ls
          1.6.1
          1.8.2
->       system
$ dvm use 1.6.1
Now using Docker 1.6.1
$ dvm ls
->        1.6.1
          1.8.2
         system
$ dvm use 1.8.2
Now using Docker 1.8.2
$ dvm ls
          1.6.1
->        1.8.2
         system
```

**Comment by rgbkrk** [comment]
Nice! You can sneak a dummy travis.yml in if you like

**Comment by smashwilson** [comment]
:+1: on it

**Comment by smashwilson** [comment]
Hooray! It's green! That means our software totally works and I trust it!

**Comment by rgbkrk** [comment]
So good.

screenshot 2015-09-25 09 41 15

**Pull request merged**
